name: Create Release note

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# defaults:
#   run:
#     working-directory: tsue_sandbox/
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: ls -la
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: functions/yarn.lock
    - name: yarn install!
      shell: bash    
      run: yarn install --frozen-lockfile
    - name: Dump release note
      id: release_note
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "RELEASE_NOTE<<$EOF" >> $GITHUB_ENV
        curl -X GET -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'X-GitHub-Api-Version: 2022-11-28' https://api.github.com/repos/${{ github.repository }}/releases/latest >> $GITHUB_ENV
        echo "$EOF" >> $GITHUB_ENV
    - name: Set Title
      id: set_title
      run: echo "TITLE=Release $(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: Set Date
      id: set_date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: Generate release note
      run: yarn run release-note
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}